version: '3'

services:
  httpd:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"